### PR TITLE
Adding combat-seq to sva

### PR DESCRIPTION
**Pull request by zhangyuqing**
Hi, Team of sva.
My name is Yuqing, I work with Evan @wevanjohnson on batch effect adjustment methods. We recently developed an improved model of ComBat, called ComBat-Seq, which we are hoping to include in sva. ComBat-Seq estimates batch effects with a negative binomial regression model, and provides adjusted data in integer counts, and therefore, it is especially useful for RNA-Seq count data. I have added the Combat-Seq scripts, examples, unit tests, and illustrations in the vignette in this pull request.
We sincerely hope you would approve of our request. Please let me know if you have any questions. 
Thanks!
Yuqing

### CODE REVIEW

**Comment by wevanjohnson** [comment]
Hi Jeff, 

We have just completed our ComBat-Seq method and have submitted it via a pull request to the sva repository! The method is now on bioarxiv and we just submitted the manuscript! Would you be able to pull these changes in and get them into the next version of Bioconductor (whenever it is, March-May 2020). Here is the bioarxiv: 

https://www.biorxiv.org/content/10.1101/2020.01.13.904730v1

Thanks!

Evan

**Comment by lcolladotor** [comment]
What do you want to do @jtleek? If it's about merging their PR and shipping it to BioC I can help you with those steps.

**Comment by wevanjohnson** [comment]
Jeff and Leonardo, 

Following up on this: Pull request #39 (Jan 2020) is a crucial addition that has been a long-time coming: ComBat-Seq. The paper is under review. If we can’t get this pull request approved and into BioC by the deadline in a few weeks, we will have to reference our GitHub repo in the paper instead of the "sva" package, which we don’t want to do.  

Also, note that our pull request #33 from 2017 is still open as well. 

I know you are busy, I completely understand. But since you are our gatekeeper for managing our ComBat software we need your help in getting these issues worked out. Thanks for your timely response on this. 

Evan

**Comment by jtleek** [comment]
Evan -

Gak I'm so sorry about this. Lots of different balls in the air as usual.
I'd rather not be a gatekeeper so I just added you and Yuqing as
collaborators. Once you accept the invite you should be able to push!

I hope you are all safe and healthy and distancing!

Jeff

**Comment by wevanjohnson** [comment]
Great! Thank you!

**Pull request merged**
